verbose: false
model: gpt-4o-mini
contextDirectories:
  - .kodrdriv/context
commit:
  add: true
  cached: true
  sendit: true
release:
  from: main
  to: HEAD
publish:
  mergeMethod: squash
  dependencyUpdatePatterns: ["@theunwalked/*", "@riotprompt/*"]
  requiredEnvVars: ["NODE_AUTH_TOKEN"]
link:
  scopeRoots:
    "@theunwalked": "../../SemicolonAmbulance"
    "@riotprompt": "../../StJustReckoning"
  workspaceFile: "pnpm-workspace.yaml"
