ignoredBuiltDependencies:
  - audify
overrides:
  '@riotprompt/riotprompt': link:../../StJustReckoning/riotprompt
  '@theunwalked/cardigantime': link:../../SemicolonAmbulance/cardigantime
  '@theunwalked/unplayable': link:../../SemicolonAmbulance/unplayable
